### PR TITLE
Export MaxOS parameter

### PR DESCRIPTION
**Pull request by psibi**
Useful for scenarios like this: https://github.com/fpco/weigh/issues/40

### CODE REVIEW

**Comment by psibi** [comment]
@chrisdone  The test fails for `lts-2` with the newly released stack with this message:

```
Stack no longer supports Cabal versions older than 1.19.2, but version 1.18.1.5 was found.  To fix this, consider updating the resolver to lts-3.0 or later / nightly-2015-05-05 or later.
```

Do you think it's worth supporting `lts-2` anymore or should I just remove that from the travis  ?

**Comment by psibi** [comment]
I had to use ugly CPP macros to make this work. Let me know if there is a better option.

**Comment by chrisdone** [comment]
How about adding the constructor for real, but having a CCP'd export list instead? This would avoid so many `#if`'s.

**Comment by psibi** [comment]
@chrisdone I have pushed new changes without the CPP hack. For unsupported GHC's, I just report `MaxOS` as zero.

**Comment by chrisdone** [comment]
That's cool. I'll merge that.

**Pull request merged**
